bucket_name           = "tf-demo-bucket-2025"
dynamodb_table_name   = "tf-lock-table"
dynamodb_hash_key     = "LockID"
lambda_function_name  = "myLambdaFunction"
lambda_handler        = "index.handler"
lambda_runtime        = "nodejs18.x"
lambda_zip            = "lambda_function.zip"